const dataObject = {
    "1": { "image": "bilder/tag1.jpg", "text": "Freiwillige Feuerwehr Grünwald", "link": "https://feuerwehr-gruenwald.de" },
    "2": { "image": "https://picsum.photos/id/12/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "3": { "image": "https://picsum.photos/id/35/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "4": { "image": "https://picsum.photos/id/120/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "5": { "image": "https://picsum.photos/id/79/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "6": { "image": "https://picsum.photos/id/8/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "7": { "image": "https://picsum.photos/id/155/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "8": { "image": "https://picsum.photos/id/167/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "9": { "image": "https://picsum.photos/id/185/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "10": { "image": "https://picsum.photos/id/10/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "11": { "image": "https://picsum.photos/id/69/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "12": { "image": "https://picsum.photos/id/112/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "13": { "image": "https://picsum.photos/id/200/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "14": { "image": "https://picsum.photos/id/245/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "15": { "image": "https://picsum.photos/id/45/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "16": { "image": "https://picsum.photos/id/17/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "17": { "image": "https://picsum.photos/id/179/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "18": { "image": "https://picsum.photos/id/202/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "19": { "image": "https://picsum.photos/id/18/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "20": { "image": "https://picsum.photos/id/44/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "21": { "image": "https://picsum.photos/id/268/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "22": { "image": "https://picsum.photos/id/1/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "23": { "image": "https://picsum.photos/id/274/1024/768/?blur", "text": "Lorem Picsum (picsum.photos)", "link": "https://picsum.photos/" },
    "24": { "image": "bilder/tag24.jpg", "text": "Frohe Weihnachten wünscht euch die Freiwillige Feuerwehr Grünwald!", "link": "https://www.feuerwehr-gruenwald.de/" }
  };